services:
    db:
        image: postgres:latest
        restart: always
        env_file: ./env
        volumes:
            - db_data:/var/lib/mysql

    web:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
            - "8010:8010" # Debugging Purposes
        env_file: ./env
        depends_on:
            - db

volumes:
    db_data:
